# Generated by Django 4.0.4 on 2022-05-31 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_marketplace', '0002_alter_product_image'),
        ('account', '0002_alter_account_options_remove_account_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_city', to='main_marketplace.city', verbose_name='Город'),
        ),
    ]
