# Generated by Django 4.0.4 on 2022-06-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hide_cellphone',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Скрыть номер телефона'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
    ]
