# Generated by Django 4.0.4 on 2022-06-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_marketplace', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/no_image_product.jpg', upload_to='product_images/', verbose_name='Изображение'),
        ),
    ]
