# Generated by Django 4.0.4 on 2022-06-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_marketplace', '0005_alter_product_main_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
